//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCKH.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPoint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPoint()
        {
            this.tblDetails = new HashSet<tblDetail>();
        }
    
        public int PointId { get; set; }
        public string Address { get; set; }
        public Nullable<float> PointX { get; set; }
        public Nullable<float> PointY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDetail> tblDetails { get; set; }
    }
}
